### ISSUE TITLE
Квадратное уравнение

### ISSUE THREAD

**Issue by ankutalev** [s-SoMka-s/19214_Chiesov#1]
1) Уберите пока сигнатуру- с Вашей я не смогу вызывать функцию от интов
2)0.0 - достаточно просто 0
3)solver (a, b, c)  - функция принимает кортеж из трех элементов, а не три элемента
перепишите на solver a b c 
4)Нет проверок на граничные случаи 0 0 2, 0 0 0

**Comment by ankutalev** [comment]
0 0 0 потеряли

**Comment by ankutalev** [comment]
| d == 0 = (x, x)

Я уж было собрался принимать, но у Вас серьезная логическая ошибка - в случае нулевого дискриминанта корни считаются неверно.

**Comment by ichiesov** [comment]
Да, чёт это сам не заметил. Подправил.

**Comment by ankutalev** [comment]
Done
